=encoding utf8

=head1 これはなに？

Nadeko はシンプルなデーモンマネージャーです。
起動すると、タスクトレイに常駐して、複数のデーモンを管理することができます。

=head1 インストール

  $ git clone git://github.com/xaicron/Nadeko.git
  $ perl Makefile.pl

=head1 使い方

Nadeko.jar と同じディレクトリに config.yaml を作成します。
中身は以下のような感じです。

  ---
  executes:
    - name: daemon1
      dir: /path/to/daemon1
      cmd:
        - daemon1
        - arg1
        - arg2
    - name: daemon2
      dir: /path/to/daemon2
      log: log/%Y-%M-%D.log
      cmd:
        - daemon1
        - arg1
        - arg2

  #-------------------------------------------------------------------
  name :    デーモン名
  cmd  :    デーモンを起動するコマンドを配列で記述
  dir  :    デーモンを起動するディレクトリ
  log  :    ログファイルのパス
            %Y/%M/%D はそれぞれ、yyyy/MM/dd に展開される

書き終えたら、Nadeko.jar をダブルクリックするなりなんなりで起動します。

=head1 Author

  xaicron
  http://blog.livedoor.jp/xaicron

=cut
